server:
  port: 8010
logging:
  level:
    root: info
    com.ofloxacin.consumer.feign.UserFeignClient: debug
spring:
  application:
    name: consumer-movie
  cloud:
    inetutils:
      ignored-interfaces:
        - docker0
        - veth.*
      preferred-networks:
        - 192.168
        - 10.0
      use-only-site-local-interfaces: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://39.96.0.238:9411
  main:
    allow-bean-definition-overriding: true
  sleuth:
    integration:
      enabled: false
    scheduled:
      enabled: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
feign:
  client:
    config:
      provider-user:
        loggerLevel: basic
  compression:
    request:
      enabled: true
      mime-types:
        - text/xml
        - application/xml
        - application/json
      min-request-size: 1024
    response:
      enabled: true
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
